//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeriaPaymentTest.AmeriaVposService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentClientClass", Namespace="payments.ameriabank.am/PaymentsClientClass")]
    [System.SerializableAttribute()]
    public partial class PaymentClientClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardHolderIDField;
        
        private string ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpaqueField;
        
        private int OrderIDField;
        
        private string PasswordField;
        
        private decimal PaymentAmountField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string backURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardHolderID {
            get {
                return this.CardHolderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CardHolderIDField, value) != true)) {
                    this.CardHolderIDField = value;
                    this.RaisePropertyChanged("CardHolderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIDField, value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opaque {
            get {
                return this.OpaqueField;
            }
            set {
                if ((object.ReferenceEquals(this.OpaqueField, value) != true)) {
                    this.OpaqueField = value;
                    this.RaisePropertyChanged("Opaque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((this.PaymentAmountField.Equals(value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string backURL {
            get {
                return this.backURLField;
            }
            set {
                if ((object.ReferenceEquals(this.backURLField, value) != true)) {
                    this.backURLField = value;
                    this.RaisePropertyChanged("backURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultPaymentClass", Namespace="payments.ameriabank.am/ResultPaymentClass")]
    [System.SerializableAttribute()]
    public partial class ResultPaymentClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RespcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespmessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIDField, value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Respcode {
            get {
                return this.RespcodeField;
            }
            set {
                if ((this.RespcodeField.Equals(value) != true)) {
                    this.RespcodeField = value;
                    this.RaisePropertyChanged("Respcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respmessage {
            get {
                return this.RespmessageField;
            }
            set {
                if ((object.ReferenceEquals(this.RespmessageField, value) != true)) {
                    this.RespmessageField = value;
                    this.RaisePropertyChanged("Respmessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentFields", Namespace="payments.ameriabank.am/PaymentFieldsClass")]
    [System.SerializableAttribute()]
    public partial class PaymentFields : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal approveamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cardholderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cardnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clientnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal depositamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opaqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte orderstatuscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int paymenttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal refundamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal rewardpointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rrnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string terminalidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trxnDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal approveamount {
            get {
                return this.approveamountField;
            }
            set {
                if ((this.approveamountField.Equals(value) != true)) {
                    this.approveamountField = value;
                    this.RaisePropertyChanged("approveamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string authcode {
            get {
                return this.authcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.authcodeField, value) != true)) {
                    this.authcodeField = value;
                    this.RaisePropertyChanged("authcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cardholderID {
            get {
                return this.cardholderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.cardholderIDField, value) != true)) {
                    this.cardholderIDField = value;
                    this.RaisePropertyChanged("cardholderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cardnumber {
            get {
                return this.cardnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.cardnumberField, value) != true)) {
                    this.cardnumberField = value;
                    this.RaisePropertyChanged("cardnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientname {
            get {
                return this.clientnameField;
            }
            set {
                if ((object.ReferenceEquals(this.clientnameField, value) != true)) {
                    this.clientnameField = value;
                    this.RaisePropertyChanged("clientname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyField, value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string datetime {
            get {
                return this.datetimeField;
            }
            set {
                if ((object.ReferenceEquals(this.datetimeField, value) != true)) {
                    this.datetimeField = value;
                    this.RaisePropertyChanged("datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal depositamount {
            get {
                return this.depositamountField;
            }
            set {
                if ((this.depositamountField.Equals(value) != true)) {
                    this.depositamountField = value;
                    this.RaisePropertyChanged("depositamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descr {
            get {
                return this.descrField;
            }
            set {
                if ((object.ReferenceEquals(this.descrField, value) != true)) {
                    this.descrField = value;
                    this.RaisePropertyChanged("descr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantid {
            get {
                return this.merchantidField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantidField, value) != true)) {
                    this.merchantidField = value;
                    this.RaisePropertyChanged("merchantid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string opaque {
            get {
                return this.opaqueField;
            }
            set {
                if ((object.ReferenceEquals(this.opaqueField, value) != true)) {
                    this.opaqueField = value;
                    this.RaisePropertyChanged("opaque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                if ((object.ReferenceEquals(this.orderidField, value) != true)) {
                    this.orderidField = value;
                    this.RaisePropertyChanged("orderid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte orderstatuscode {
            get {
                return this.orderstatuscodeField;
            }
            set {
                if ((this.orderstatuscodeField.Equals(value) != true)) {
                    this.orderstatuscodeField = value;
                    this.RaisePropertyChanged("orderstatuscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_state {
            get {
                return this.payment_stateField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_stateField, value) != true)) {
                    this.payment_stateField = value;
                    this.RaisePropertyChanged("payment_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paymenttype {
            get {
                return this.paymenttypeField;
            }
            set {
                if ((this.paymenttypeField.Equals(value) != true)) {
                    this.paymenttypeField = value;
                    this.RaisePropertyChanged("paymenttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal refundamount {
            get {
                return this.refundamountField;
            }
            set {
                if ((this.refundamountField.Equals(value) != true)) {
                    this.refundamountField = value;
                    this.RaisePropertyChanged("refundamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respcode {
            get {
                return this.respcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.respcodeField, value) != true)) {
                    this.respcodeField = value;
                    this.RaisePropertyChanged("respcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal rewardpoint {
            get {
                return this.rewardpointField;
            }
            set {
                if ((this.rewardpointField.Equals(value) != true)) {
                    this.rewardpointField = value;
                    this.RaisePropertyChanged("rewardpoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rrn {
            get {
                return this.rrnField;
            }
            set {
                if ((object.ReferenceEquals(this.rrnField, value) != true)) {
                    this.rrnField = value;
                    this.RaisePropertyChanged("rrn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stan {
            get {
                return this.stanField;
            }
            set {
                if ((object.ReferenceEquals(this.stanField, value) != true)) {
                    this.stanField = value;
                    this.RaisePropertyChanged("stan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string terminalid {
            get {
                return this.terminalidField;
            }
            set {
                if ((object.ReferenceEquals(this.terminalidField, value) != true)) {
                    this.terminalidField = value;
                    this.RaisePropertyChanged("terminalid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trxnDetails {
            get {
                return this.trxnDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.trxnDetailsField, value) != true)) {
                    this.trxnDetailsField = value;
                    this.RaisePropertyChanged("trxnDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespMessage", Namespace="payments.ameriabank.am/RespMessage")]
    [System.SerializableAttribute()]
    public partial class RespMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpaqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespmessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opaque {
            get {
                return this.OpaqueField;
            }
            set {
                if ((object.ReferenceEquals(this.OpaqueField, value) != true)) {
                    this.OpaqueField = value;
                    this.RaisePropertyChanged("Opaque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respcode {
            get {
                return this.RespcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RespcodeField, value) != true)) {
                    this.RespcodeField = value;
                    this.RaisePropertyChanged("Respcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respmessage {
            get {
                return this.RespmessageField;
            }
            set {
                if ((object.ReferenceEquals(this.RespmessageField, value) != true)) {
                    this.RespmessageField = value;
                    this.RaisePropertyChanged("Respmessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://payments.ameriabank.am", ConfigurationName="AmeriaVposService.IAmeria")]
    public interface IAmeria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payments.ameriabank.am/IAmeria/GetPaymentID", ReplyAction="http://payments.ameriabank.am/IAmeria/GetPaymentIDResponse")]
        AmeriaPaymentTest.AmeriaVposService.ResultPaymentClass GetPaymentID(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payments.ameriabank.am/IAmeria/GetPaymentFields", ReplyAction="http://payments.ameriabank.am/IAmeria/GetPaymentFieldsResponse")]
        AmeriaPaymentTest.AmeriaVposService.PaymentFields GetPaymentFields(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payments.ameriabank.am/IAmeria/ReversePayment", ReplyAction="http://payments.ameriabank.am/IAmeria/ReversePaymentResponse")]
        AmeriaPaymentTest.AmeriaVposService.RespMessage ReversePayment(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payments.ameriabank.am/IAmeria/Confirmation", ReplyAction="http://payments.ameriabank.am/IAmeria/ConfirmationResponse")]
        AmeriaPaymentTest.AmeriaVposService.RespMessage Confirmation(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payments.ameriabank.am/IAmeria/Refund", ReplyAction="http://payments.ameriabank.am/IAmeria/RefundResponse")]
        AmeriaPaymentTest.AmeriaVposService.RespMessage Refund(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://payments.ameriabank.am/IAmeria/UpdateOpaque", ReplyAction="http://payments.ameriabank.am/IAmeria/UpdateOpaqueResponse")]
        AmeriaPaymentTest.AmeriaVposService.RespMessage UpdateOpaque(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmeriaChannel : AmeriaPaymentTest.AmeriaVposService.IAmeria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmeriaClient : System.ServiceModel.ClientBase<AmeriaPaymentTest.AmeriaVposService.IAmeria>, AmeriaPaymentTest.AmeriaVposService.IAmeria {
        
        public AmeriaClient() {
        }
        
        public AmeriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmeriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmeriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmeriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AmeriaPaymentTest.AmeriaVposService.ResultPaymentClass GetPaymentID(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields) {
            return base.Channel.GetPaymentID(paymentfields);
        }
        
        public AmeriaPaymentTest.AmeriaVposService.PaymentFields GetPaymentFields(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields) {
            return base.Channel.GetPaymentFields(paymentfields);
        }
        
        public AmeriaPaymentTest.AmeriaVposService.RespMessage ReversePayment(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields) {
            return base.Channel.ReversePayment(paymentfields);
        }
        
        public AmeriaPaymentTest.AmeriaVposService.RespMessage Confirmation(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields) {
            return base.Channel.Confirmation(paymentfields);
        }
        
        public AmeriaPaymentTest.AmeriaVposService.RespMessage Refund(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields) {
            return base.Channel.Refund(paymentfields);
        }
        
        public AmeriaPaymentTest.AmeriaVposService.RespMessage UpdateOpaque(AmeriaPaymentTest.AmeriaVposService.PaymentClientClass paymentfields) {
            return base.Channel.UpdateOpaque(paymentfields);
        }
    }
}
